### ISSUE TITLE
support for AUX Channel (WHO=9)

### ISSUE THREAD

**Issue by k0nti** [mvalla/openhab-addons#12]
It would be nix to have a integraten of the AUX Channels 

WHO 9

bg Patrick

**Comment by fmalfatto** [comment]
It would be great for me also! I still have the 3486 burglar-alarm unit and that's the only way I can manage it because it's not well covered by phone field. MHS1 does no more support  it.

**Comment by mvalla** [comment]
Can you provide a link to the official documentation of this WHO ?
I have looked in the BTicino MyOpen web site (https://www.myopen-legrandgroup.com/developers/), but this WHO apparently does not exist.
Without a proper documentation, is very difficult to implement support for AUX channels.

**Comment by fmalfatto** [comment]
It should be  under the who=5 section, but I did find the document they are referring here:
https://www.myopen-legrandgroup.com/forums/topic/frame-who9-in-alarm/

**Comment by Gozilla01** [comment]
See official documentation WHO = 5 on page 7 and 8
     [Who] * [WHAT] * [WHERE] ## AUX commands
     [WHO] = 9 AUX
     [WHAT] = 0-10 See Table
     [WHERE] = 1-9 AUX number
     
     Example set status:
     * 9 * 0 * 7 ## Sets the AUX 7 to 0 (OFF)
     * 9 * 1 * 7 ## Set to 1 (ON) the AUX 7
     Others [WHAT] 2-10 I do not know what they are for,
     I can not find any documentation on the network.
     The MyHOME_Suite suite also does not have a [WHAT] 2-10 configuration
     
     Example reading status
     * # [Who] * [WHERE] ##
     * # 9 * 7 ## Displays AUX status 7
     Responds * 9 [WHAT] * [WHERE] ##
     
     Example reading of all states
     * # [Who] * 0 ##
     * # 9 * 0 ## It responds with all the AUX states
     Responds * 9 [WHAT] * [WHERE] ##
     I do not know how to detect the lights automatically but it could
     use * # 9 * 0 ## to detect AUXs
    
     Auxiliary WHAT values:
     OFF -> 0 = Off
     ON -> 1 = On
     TOGGLE -> 2
     STOP -> 3
     UP -> 4
     DOWN -> 5
     ENABLED -> 6
     DISABLED -> 7
     RESET_GEN -> 8
     RESET_BI -> 9
     RESET_TRI -> 10

**Comment by Gozilla01** [comment]
Look here
[https://community.openhab.org/t/bticino-openwebnet-adding-aux-commands-design/58035/6](url)

**Comment by mickymix** [comment]
I would appreciate the investigation on WHO=9 too, as I have some presence sensors (L4610) which I use to switch on lights... but would like to take control of them... if I can be of any help with logs, just let me know... I'll do my best to send them...

**Comment by Gozilla01** [comment]
@mickymix 
If you send logs it would be very nice together with a description.

**Comment by Gozilla01** [comment]
See pull request [58](https://github.com/mvalla/openhab2-addons/pull/58)

**Comment by Gozilla01** [comment]
Remove label question

**Comment by mvalla** [comment]
Some discussion: https://www.domoticz.com/forum/viewtopic.php?t=14053&start=40

**Comment by mvalla** [comment]
sending AUX commands is supported by the [official openwebnet binding](https://www.openhab.org/addons/bindings/openwebnet/)
