### ISSUE TITLE
some F429 dimmers are not discovered

### ISSUE THREAD

**Issue by weltraumbagger** [mvalla/openhab-addons#14]
i´ve serveral dimmers, connected to two f429 dali-interface on different interfaces (8 dimmers in ..`#4#01` and seven dimmers in ..`#4#02`. 

if i start device discovery (meanwhile several times) some dimmers are not found (all in ..`#4#01`), even not as switch if powered off. if i add them manually they work.

but all dimmers (enen the discovered) do not work quite correct:

under "paper ui / control" i can see the dimmer and slide light on, off and dimm it. but if i control from another point (light switch or domotica-app for example) the state will not be updated here. 

as in improvement i suggest not only a slider for dimmers, a additionally switch would be great go enable switching light on and automatically use last dimmer-state. so if automatic discovery woudl find both, switch and dimmer, i think would be a good thing.

**Comment by mvalla** [comment]
@m4rky-m4rk and @weltraumbagger I think this is a very old issue and it was never unerstood if the problem was with hw or with the binding. I think I will close this one as no more evidence is available that is a problem with the binding.

**Comment by weltraumbagger** [comment]
I totally agree.
This happened a long time ago, meanwhile i do not use autodiscovery but have textual config and so never seen this issue again
thank you

13.04.2023 22:15:51 M Valla ***@***.***>:
