### ISSUE TITLE
Dimmer100 1%-steps support

### ISSUE THREAD

**Issue by weltraumbagger** [mvalla/openhab-addons#24]
actually the dimmer100 steps are 10% now. with a physical switch step is 5%, and on 4893 touchscreen there are 1%-steps when using the slider

remark to think about: if having two things: dimmer10 and dimmer100, each should recognize the on/off commands from both. because it is possible the user switches one light for example from a touchscreen where light is configured as dimmer100 and the same light from a switch where the light may be configured as dimmer10.

**Comment by mvalla** [comment]
issue moved to https://github.com/openhab/openhab-addons/issues/8514. Closing this.
