### ISSUE TITLE
thermo: add support for scene 1 to 16

### ISSUE THREAD

**Issue by Gozilla01** [mvalla/openhab-addons#85]
As per request of @Tommyshome
add support for scene 1 to 16  on the 3550 plant
For example this Heating scene 1 activation command:
`*4*1201*#0##`
**what** = [1201-1216]

![thermoscene](https://user-images.githubusercontent.com/44798080/57007555-ca792600-6be9-11e9-89a2-1a2da9a89a7e.png)

**Comment by mvalla** [comment]
thermo scenarios are supported in the [official openwebnet binding](https://www.openhab.org/addons/bindings/openwebnet/)
