### ISSUE TITLE
[feature] Support for backup connection - openwebnet binding

### ISSUE THREAD

**Issue by Andrew082** [mvalla/openhab-addons#94]
Hi Massi!

I was wondering if it's possible to have a "backup connection" feature, a secondary IP/port/password of another un/official Btcicino/Legrand gatway. In case of a faulty "primary" gateway then the Binding could try to connecto to a "secondary" gateway. 

Something like this ... (f. i.)

```
Bridgeopenwebnet:bus_gateway:casa_mhscreen10 MyHOMEScreen10 [
primary_host=10.2.82.4,
primary_passwd=12345,
primary_port=20000,
primary_discoveryByActivation=false,
secondary_host=10.2.82.5,
secondary_passwd=12345,
secondary_port=20000,
secondary_discoveryByActivation=false,
							]{
my stuff....
}
```

Keep up with this great binding!!

Regards!

**Comment by mvalla** [comment]
The binding has already an automatic reconnect feature that tries to reconnect to the currently configured gateway. 

I do not see so likely that the primary gateway gets “faulty”.
What you can do is add the second gw to the config file , leave it commented, and activate it very quickly in case the primary GW fails.
But I do not see a real need to make it automatic.
What is exactly your use-case or situation?

**Comment by Andrew082** [comment]
Hi Massi,

in some cases I had my homescreen offline due to tripped breaker (not the same as the E46ADCN). Some times I do some test with my home screen (reprogramming it) and, in this case, I have no comunication with the bus.
As you said such feature is not vital... It could be handy for me but of course it's just an optional feature... Maybe someone else could take advantage

**Comment by m4rky-m4rk** [comment]
Maybe it helps someone ... I created some rules and a script that automatically detects an offline gateway Thing and restarts it.

https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377/1070?u=m4rk

**Comment by mvalla** [comment]
Closing this as it's not an important feature (wontfix)
