### ISSUE TITLE
Zigbee USB gateway (stick) stops receiving messages

### ISSUE THREAD

**Issue by feodor85** [mvalla/openhab-addons#95]
I have a Zigbee USB gateway (stick Legrand 088328). Version 1.4.5. 

I set up OpenWebNet binding. After loading everything works. 
But after some time, receiving messages from devices stops. 
After some testing, it appears that the data from the stick is not received enymore by the binding after this line in the logs:

`2019-10-17 00:18:45.860 [INFO ] [org.openwebnet.OpenGatewayZigBee$a ] - SERIAL RECEIVED <<<<<<<<<<<<<<<<<<<<<<<< *#1000*769090600#9*94##`

Rebooting makes the binding receive messages again from the stick..

**Comment by mvalla** [comment]
It's a bug in the ZigBee-OpenWebNet receiving part of the binding. It will be corrected in the next binding release.

**Comment by mvalla** [comment]
Fixed in 2.5.0.M4
