### ISSUE TITLE
ZigBee USB Gateway serial port configuration via .things file

### ISSUE THREAD

**Issue by feodor85** [mvalla/openhab-addons#96]
I config Legrand ZigBee USB Gateway via .thing file
`Bridge openwebnet:zb_gateway:myZBgateway "ZigBee USB Gateway" [serialPort="/dev/legrand_usb"] {...} `

port setup does not work : port /dev/ttyACM0 is always used. 
Since the port is not always the same, configuration of the serial port should be possible.

**Comment by mvalla** [comment]
closing this as it is now supported in the official openwebnet binding
