### ISSUE TITLE
Status after reboot

### ISSUE THREAD

**Issue by feodor85** [mvalla/openhab-addons#98]
I config Legrand ZigBee USB Gateway.

After rebooting raspberry with openhab2 the status of OWN devices is not reread.
Status is displayed only after turning the device on or off.

It may be necessary to re-read the status of the device after a reboot.
For the light:
```
*#1*769636101#9##
```
I did not find an example for the roller shutter, but I hope there is a command too.

**Comment by mvalla** [comment]
solved on the official openwebnet binding OH 3.1M4
